name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/blood-donor-alert-system
            git pull origin main
            sudo docker build -t lifelink-app .
            sudo docker stop lifelink-container || true
            sudo docker rm lifelink-container || true
            sudo docker run -d -p 5000:5000 --name lifelink-container lifelink-app
